#if !canImport(ObjectiveC)
import XCTest

extension EqualTokenSpacingFormatterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EqualTokenSpacingFormatterTests = [
        ("testVisitToken", testVisitToken),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(EqualTokenSpacingFormatterTests.__allTests__EqualTokenSpacingFormatterTests),
    ]
}
#endif
